package com.androidcargo.spring.models.work;

import lombok.Getter;
import lombok.Setter;

public enum WorkType {
  FURNITURE_MOVING, OFFICE_MOVING, BUILDING_MATERIALS_MOVING, WASTE_MOVING, RIGGING_WORK, LIGHT_OBJECTS_MOVING, WORK_AT_HEIGHT, DIGGING_WORKS, SNOW_REMOVAL, DOG_WALKING, MOWING_GRASS, MOVING_SHIFT_WORK;
}
